### ISSUE TITLE
Request for new version Release

### ISSUE THREAD

**Issue by UsamaSadiq** [fle/django-multi-email-field#23]
## Description
A fix https://github.com/fle/django-multi-email-field/pull/20 needed for `Django 4.0` support/compatibility was merged in the repo in May. Currently, this package dependency is a blocker in upgrading to `Django 4.2` because the fix hasn't been released yet.

Could you please release a new PyPI version of the package to resolve the blocker in `Django 4.2` upgrade for openedx and other entities dependant on this package? Thanks.

**Comment by UsamaSadiq** [comment]
Hi @SebCorbin if you have access, could you publish new package version please. Thanks.

**Comment by SebCorbin** [comment]
Released 0.7.0
