### ISSUE TITLE
0.5 not working on pip

### ISSUE THREAD

**Issue by lociii** [fle/django-multi-email-field#5]
[localhost] out: pip.exceptions.DistributionNotFound: No matching distribution found for django-multi-email-field==0.5

**Comment by g-as** [comment]
Yup. @fle I guess something went wrong with your PyPI upload

**Comment by paultcochrane** [comment]
Same issue here.  Would be good to be able to install version 0.5 via pip.

**Comment by costela** [comment]
PR #8 tries to explain the origin and a solution to this problem.

For those in a hurry, we're added a repackaged version of exactly the same package here: https://pypi.python.org/pypi/django-multi-email-field_rerelease
(this package will be removed some time after @fle makes a new release to pypi)
